[package]
name = "slowdrive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.18.0", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.36.0"
rand = "0.9.2"
rand_xorshift = "0.4.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
